name: 'check-eslint-stylelint-action'

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Install modules
        run: pnpm install
      - name: Run ESLint
        run: pnpm lint:js && pnpm lint:style
